// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSExtensionForMomentum
{
	internal sealed partial class Vsix
	{
		public const string Id = "VSExtensionForMomentum.9add7f25-b6c6-4f78-bdef-b2ca1319876a";
		public const string Name = "VSExtensionForMomentum";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "Andrey Lityagin";
		public const string Tags = "";
	}
}
