// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace VSExtensionForMomentum
{
	/// <summary>
	/// Helper class that exposes all GUIDs used across VS Package.
	/// </summary>
	internal sealed partial class PackageGuids
	{
		public const string VSExtensionForMomentumString = "a8833f24-18b7-4a3c-b2b9-d1a3b6a45b58";
		public static Guid VSExtensionForMomentum = new Guid(VSExtensionForMomentumString);
	}
	/// <summary>
	/// Helper class that encapsulates all CommandIDs uses across VS Package.
	/// </summary>
	internal sealed partial class PackageIds
	{
		public const int MyMenuGroup = 0x0001;
		public const int ReplaceBinaryFiles = 0x0100;
		public const int ReplaceSupervisorFiles = 0x0200;
		public const int ReplaceCustomFolderFiles = 0x0300;
	}
}